'use client'

import { useMemo, useState } from 'react'
import { projects } from '@/content/projects'
import { askHugo } from '@/lib/hugo'
import type { HugoResult } from '@/lib/types'

const prompts = ['Which projects use AI?', 'Show me web projects', 'Who is Daniel?']

function ProjectCard({ project }: { project: (typeof projects)[number] }) { return <article className="group flex flex-col justify-between border border-line bg-surface p-5 transition duration-300 hover:-translate-y-1 hover:border-orange md:p-6"><div><div className="mb-12 flex items-start justify-between"><span className="mono text-[10px] uppercase tracking-[.2em] text-orange">{project.category}</span><span className="text-muted transition group-hover:text-orange">↗</span></div><h3 className="text-2xl font-medium tracking-tight">{project.name}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-muted">{project.description}</p></div><div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4"><div className="flex flex-wrap gap-2">{project.stack.map((item) => <span key={item} className="mono text-[10px] text-muted">{item}</span>)}</div><a href={project.github} target="_blank" rel="noreferrer" className="mono inline-flex items-center gap-1 text-[10px] uppercase tracking-widest text-text hover:text-orange">source</a></div></article> }

export default function Home() { const [open, setOpen] = useState(false); const [question, setQuestion] = useState(''); const [result, setResult] = useState<HugoResult | null>(null); const featured = projects.filter((p) => p.featured); const submit = (value = question) => { if (!value.trim()) return; setResult(askHugo(value)); setQuestion(value) }; const year = useMemo(() => new Date().getFullYear(), []); return <main>
  <header className="fixed left-0 right-0 top-0 z-50 border-b border-line/70 bg-ink/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><a href="#top" className="mono text-xs font-bold tracking-[.18em]">DB<span className="text-orange">.</span></a><nav className="hidden items-center gap-8 md:flex"><a href="#work" className="mono text-[11px] uppercase tracking-widest text-muted hover:text-text">Work</a><a href="#about" className="mono text-[11px] uppercase tracking-widest text-muted hover:text-text">About</a><a href="#hugo" className="mono text-[11px] uppercase tracking-widest text-muted hover:text-text">Ask Hugo</a></nav><button aria-label="Toggle menu" onClick={() => setOpen(!open)} className="md:hidden">{open ? '×' : '☰'}</button></div>{open && <nav className="flex flex-col gap-5 border-t border-line bg-ink px-5 py-6 md:hidden"><a href="#work" onClick={() => setOpen(false)}>Work</a><a href="#about" onClick={() => setOpen(false)}>About</a><a href="#hugo" onClick={() => setOpen(false)}>Ask Hugo</a></nav>}</header>
  <section id="top" className="grid-paper noise relative flex min-h-[760px] items-end overflow-hidden px-5 pb-20 pt-36 md:px-8 md:pb-28"><div className="mx-auto w-full max-w-7xl"><div className="mb-8 flex items-center gap-3"><span className="size-2 rounded-full bg-orange" /><span className="mono text-[11px] uppercase tracking-[.22em] text-muted">Developer · Builder · Explorer</span></div><h1 className="display max-w-5xl text-[clamp(4.3rem,11vw,10.5rem)] font-semibold">I build<br /><span className="text-orange">intelligent</span><br />software.</h1><div className="mt-12 flex max-w-2xl flex-col justify-between gap-8 border-t border-line pt-5 md:flex-row"><p className="max-w-md text-base leading-7 text-muted">Interfaces, data and AI brought together to create useful digital experiences with a human point of view.</p><a href="#work" className="mono inline-flex items-center gap-2 text-xs uppercase tracking-widest text-text hover:text-orange">Explore selected work ↗</a></div></div></section>
  <section className="border-y border-line px-5 py-5 md:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-x-8 gap-y-3 mono text-[10px] uppercase tracking-[.18em] text-muted"><span>IDEA</span><span className="text-orange">→</span><span>DATA</span><span className="text-orange">→</span><span>AI</span><span className="text-orange">→</span><span>CODE</span><span className="text-orange">→</span><span>PRODUCT</span><span className="text-orange">→</span><span>IMPACT</span></div></section>
  <section id="work" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><div className="mb-12 flex items-end justify-between gap-5"><div><p className="mono mb-4 text-[10px] uppercase tracking-[.2em] text-orange">01 / Selected work</p><h2 className="display text-5xl font-medium md:text-7xl">Things I&apos;ve<br />been building.</h2></div><span className="mono hidden text-xs text-muted md:block">{projects.length.toString().padStart(2,'0')} projects / curated</span></div><div className="grid gap-4 md:grid-cols-3">{featured.map((project) => <ProjectCard key={project.slug} project={project} />)}</div><div className="mt-4 grid gap-4 md:grid-cols-2">{projects.filter((p) => !p.featured).map((project) => <ProjectCard key={project.slug} project={project} />)}</div></section>
  <section id="hugo" className="border-y border-line bg-surface px-5 py-24 md:px-8 md:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="mono mb-4 text-[10px] uppercase tracking-[.2em] text-orange">02 / The guide</p><h2 className="display text-5xl font-medium md:text-7xl">Ask<br />HUGO<span className="text-orange">.</span></h2><p className="mt-6 max-w-sm text-sm leading-6 text-muted">A curated guide to Daniel&apos;s work. Ask a question and get the projects that make the most sense — with their source links.</p></div><div className="border border-line bg-ink p-5 md:p-8"><div className="mb-8 flex items-center gap-3"><span className="text-orange">✦</span><span className="mono text-[10px] uppercase tracking-widest text-muted">HUGO / portfolio intelligence</span></div><div className="flex flex-wrap gap-2">{prompts.map((prompt) => <button key={prompt} onClick={() => submit(prompt)} className="border border-line px-3 py-2 text-left text-xs text-muted transition hover:border-orange hover:text-text">{prompt}</button>)}</div>{result && <div className="mt-8 border-l-2 border-orange pl-4"><p className="text-sm leading-6 text-text">{result.answer}</p>{result.projects.length > 0 && <div className="mt-5 grid gap-3">{result.projects.map((project) => <a key={project.slug} href={project.github} target="_blank" rel="noreferrer" className="flex items-center justify-between border border-line p-3 hover:border-orange"><span><strong className="text-sm">{project.name}</strong><span className="ml-3 mono text-[10px] text-muted">{project.category}</span></span><span className="text-orange">↗</span></a>)}</div>}</div>}<form onSubmit={(event) => { event.preventDefault(); submit() }} className="mt-8 flex border-b border-line pb-2"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about a project, skill or idea..." className="min-w-0 flex-1 bg-transparent text-sm text-text outline-none placeholder:text-muted" /><button aria-label="Ask Hugo" className="text-orange hover:text-text"></button></form></div></div></section>
  <section id="about" className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-32"><div className="grid gap-12 md:grid-cols-2"><div><p className="mono mb-4 text-[10px] uppercase tracking-[.2em] text-orange">03 / About</p><h2 className="display text-5xl font-medium md:text-7xl">Curious by<br />default.</h2></div><div className="max-w-lg text-base leading-8 text-muted"><p>I&apos;m Daniel Beni, a developer building at the intersection of technology and real-world usefulness. I care about the detail in the interface, the clarity of the system and the people it serves.</p><p className="mt-6">This portfolio is a living laboratory — a place for shipped work, experiments and the questions that lead to better products.</p><div className="mt-8 flex gap-5"><a href="https://github.com/DanielBeni-tech" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-text hover:text-orange">GitHub</a><a href="mailto:contact@danielbeni.dev" className="inline-flex items-center gap-2 text-sm text-text hover:text-orange"> Contact</a></div></div></div></section>
  <footer className="border-t border-line px-5 py-6 md:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 mono text-[10px] uppercase tracking-widest text-muted md:flex-row"><span>Daniel Beni © {year}</span><span>Built with intent / Cameroon</span><a href="https://github.com/DanielBeni-tech" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 hover:text-orange">github ↗</a></div></footer>
</main> }
