export const profileEn = {
  name: 'Daniel Beni Mpodol Welisan',
  firstName: 'DANIEL BENI',
  lastName: 'MPODOL WELISAN',
  alias: 'Telecom engineering student · Fullstack & Lead Developer · UX/UI · AI',
  title: 'Telecom engineering student · Fullstack & Lead Developer · Frontend & UX/UI · AI Engineer',
  fullTitle: 'Telecom engineering student · Fullstack · Frontend & UX/UI · AI',
  location: 'Yaoundé / Cameroon',
  description:
    'Telecommunications engineering student, fullstack lead (JavaScript and Python), with a real focus on frontend, UI/UX and user journeys.',
  summary: 'I design, connect and run systems — from the user journey to the network.',
  bio: "3rd-year engineering student at SUP'PTIC, freelance since 2023. I lead projects as fullstack and lead developer: interface, appflow, API and production. Telecom training adds networks, embedded/IoT and security.",
  aboutStory: [
    {
      year: '2022 — 2023',
      title: 'Web development',
      text: 'Moved to the web: frontend basics and first products.',
      image: '/photos/daniel-desk.webp',
    },
    {
      year: '2023 — present',
      title: 'Freelance',
      text: 'First clients right after the web training: sites, apps and interfaces, independently and alongside studies.',
      image: '/illustrations/freelance.webp',
    },
    {
      year: '2023 — 2025',
      title: 'Robotics and embedded systems',
      text: 'First hands-on training: robotics and embedded, already in the hardware.',
      image: '/photos/electronique.webp',
    },
    {
      year: '2024 — present',
      title: 'Telecommunications engineering',
      text: "At SUP'PTIC Yaoundé, 3rd year — Telecommunications Works Engineer, Computing & Networks.",
      image: '/photos/daniel-supptic.webp',
    },
    {
      year: '2026',
      title: 'CAMTEL internship, competitions & AMD',
      text: 'Fullstack lead on CARBURFLOW, competitions (Orange Business Game, JUIN / Cursor Cameroon, Hackverse), then AMD AI Academy Challenge.',
      image: '/projects/carburflow-alerts.webp',
      image2: '/photos/amd-ai-academy.webp',
    },
  ],
  whatIOffer:
    'I take fullstack lead on the products I ship: frontend, UX/UI, backend and deploy. The AMD challenge extends this toward LLMs, RAG and AI agents, with a network and security culture from telecom.',
  currentFocus: [
    'Fullstack lead — frontend, UX/UI and backend',
    'Hugging Face LLM Course',
    'AMD AI Academy Challenge — LLMs, RAG, agents',
    'Claude Cameroon — community born in early 2026',
    "President of SUP'PTIC Computer Club (elected 2026)",
  ],
  stats: [
    { label: 'Selected projects', value: '9', project: 'CV · GitHub · competitions', image: '/illustrations/projects-grid.webp' },
    { label: 'Year of study', value: '3rd', project: "SUP'PTIC · Computing & Networks" },
    { label: 'Chess', value: '1600', project: 'Elo · plus football, scrabble, games', icon: '/photos/chess.webp' },
    { label: 'Languages', value: 'FR · B1', project: 'French · English' },
  ],
  skills: [
    {
      label: 'Development',
      items: [
        { name: 'Python', level: 'Maîtrise' },
        { name: 'JavaScript', level: 'Maîtrise' },
        { name: 'React', level: 'Maîtrise' },
        { name: 'Node.js', level: 'Intermédiaire' },
        { name: 'PostgreSQL', level: 'Intermédiaire' },
        { name: 'Docker', level: 'Intermédiaire' },
      ],
    },
    {
      label: 'UX/UI & Design',
      items: [
        { name: 'Figma', level: 'Maîtrise' },
        { name: 'Design System', level: 'Intermédiaire' },
        { name: 'Prototyping', level: 'Maîtrise' },
        { name: 'Appflow', level: 'Intermédiaire' },
      ],
    },
    {
      label: 'Networks',
      items: [
        { name: 'IPv4 / IPv6', level: 'Intermédiaire' },
        { name: 'VLAN', level: 'Intermédiaire' },
        { name: 'OSPF', level: 'En apprentissage' },
        { name: 'ACL', level: 'Intermédiaire' },
        { name: 'Site-to-site VPN', level: 'En apprentissage' },
      ],
    },
    {
      label: 'Embedded & IoT',
      items: [
        { name: 'C / C++', level: 'Intermédiaire' },
        { name: 'Arduino', level: 'Intermédiaire' },
        { name: 'ESP32', level: 'Intermédiaire' },
        { name: 'Sensors', level: 'Intermédiaire' },
      ],
    },
    {
      label: 'AI & Data',
      items: [
        { name: 'LLMs', level: 'En apprentissage' },
        { name: 'RAG', level: 'En apprentissage' },
        { name: 'AI agents', level: 'En apprentissage' },
        { name: 'Fine-tuning', level: 'En apprentissage' },
        { name: 'Scikit-learn', level: 'Intermédiaire' },
      ],
    },
    {
      label: 'Cybersecurity',
      items: [
        { name: 'Wireshark', level: 'Intermédiaire' },
        { name: 'Nmap', level: 'Intermédiaire' },
      ],
    },
  ],
  softSkills: ['Communication', 'Teamwork', 'Project management', 'Leadership'],
  languages: [
    { name: 'French', level: 'Native' },
    { name: 'English', level: 'B1' },
  ],
  phone: '+237 654 516 028',
  email: 'daniel100beni@gmail.com',
  github: 'https://github.com/DanielBeni-tech',
  linkedin: 'https://linkedin.com/in/daniel-beni',
  cvUrl: '/CV-Daniel-Beni.pdf',
  socials: [
    { label: 'GitHub', href: 'https://github.com/DanielBeni-tech', icon: 'github' },
    { label: 'LinkedIn', href: 'https://linkedin.com/in/daniel-beni', icon: 'linkedin' },
  ],
  available: true,
};

export const uiEn = {
  available: 'Available for new projects',
  availableShort: 'Available',
  talk: "Let's talk →",
  seeCv: 'View CV',
  about: 'About',
  skills: 'Skills',
  path: 'Path',
  projects: 'Projects',
  competitions: 'Competitions',
  engagement: 'Community',
  life: 'Off code',
  contact: 'Contact',
  offer: 'What I offer',
  brief: 'In short',
  keySkills: 'Key skills',
  stacks: 'Technical stack',
  focus: 'Current focus',
  readCv: 'Read the CV',
  downloadPdf: 'Download PDF',
  whatIBuild: 'What I can do',
  softSkills: 'Soft skills',
  languages: 'Languages',
  mastery: 'Mastery',
  intermediate: 'Intermediate',
  learning: 'Learning',
  experience: 'Professional experience',
  education: 'Education',
  certification: 'Certification',
  freelanceSince: 'Freelance since 2023,',
  thenAmd: 'CAMTEL internship, then AMD.',
  chosenProjects: 'Selected projects',
  shipped: 'Shipped work, including competitions.',
  all: 'All',
  github: 'GitHub',
  real: 'Shipped',
  communityLead: 'I do not only ship software.',
  communityAccent: 'I build people around technology.',
  together: 'Build together',
  competitionsNote: 'Event photos — files live in public/competitions/.',
  projectLabel: 'Project:',
  formName: 'Name',
  formEmail: 'Email',
  formSubject: 'Subject',
  formMessage: 'Message',
  formSend: 'Send',
  contactLead: 'A project in mind?',
  contactBody:
    'Fullstack lead, frontend / UX or an AI topic — the CV and GitHub say the rest. Write to me.',
  based: 'Based in',
  openToWork: 'Available for new projects',
  downloadCv: 'Download CV',
  servicesLead: 'Fullstack lead, from pixel to API.',
  servicesAccent: 'Frontend, UX, AI and telecom culture.',
  collaborate: "Let's work together",
  download: 'Download',
  scroll: 'Scroll',
  menu: 'Menu',
  rights: 'All rights reserved',
  designedIn: 'Designed and built in Yaoundé · Cameroon',
  seeProject: 'See project',
  pathMeta: 'Experience · Education · Certifications',
  projectsCount: 'projects · CV + GitHub',
  shippedLine: 'Shipped work, including competitions.',
  shippedAccent: 'SANGO at Hackverse · SYNTRA at JUIN.',
  lifeBody: 'The same taste for play: calculate, run, place a word, or stay on a screen one evening.',
  seeWork: 'See',
  write: 'Write',
  close: 'Close',
  outcomes: 'Outcomes',
  stack: 'Stack',
  code: 'Code',
  openProject: 'Open project',
};

export const uiFr = {
  available: 'Disponible pour de nouveaux projets',
  availableShort: 'Disponible',
  talk: 'Parlons-en →',
  seeCv: 'Voir le CV',
  about: 'À propos',
  skills: 'Compétences',
  path: 'Parcours',
  projects: 'Projets',
  competitions: 'Compétitions',
  engagement: 'Engagement',
  life: 'Hors code',
  contact: 'Contact',
  offer: 'Ce que je propose',
  brief: 'En bref',
  keySkills: 'Compétences clés',
  stacks: 'Stacks techniques',
  focus: 'Focus actuel',
  readCv: 'Consulter le CV',
  downloadPdf: 'Télécharger le PDF',
  whatIBuild: 'Ce que je sais faire',
  softSkills: 'Soft skills',
  languages: 'Langues',
  mastery: 'Maîtrise',
  intermediate: 'Intermédiaire',
  learning: 'En apprentissage',
  experience: 'Expérience professionnelle',
  education: 'Formation',
  certification: 'Certification',
  freelanceSince: 'Freelance depuis 2023,',
  thenAmd: 'stage CAMTEL, puis AMD.',
  chosenProjects: 'Projets choisis',
  shipped: 'Projets livrés, y compris en compétition.',
  all: 'Tous',
  github: 'GitHub',
  real: 'Produit livré',
  communityLead: 'Je ne construis pas seulement du logiciel.',
  communityAccent: 'Je construis des gens autour de la technologie.',
  together: 'Construire ensemble',
  competitionsNote: 'Photos par défaut — remplace les fichiers dans public/competitions/.',
  projectLabel: 'Projet :',
  formName: 'Nom',
  formEmail: 'Email',
  formSubject: 'Sujet',
  formMessage: 'Message',
  formSend: 'Envoyer',
  contactLead: 'Un projet en tête ?',
  contactBody:
    'Lead fullstack, frontend / UX ou un sujet IA — le CV et GitHub disent le reste. Écris-moi, on en parle.',
  based: 'Basé à',
  openToWork: 'Disponible pour de nouveaux projets',
  downloadCv: 'Télécharger le CV',
  servicesLead: 'Lead fullstack, du pixel à l’API.',
  servicesAccent: 'Frontend, UX, IA et culture télécom.',
  collaborate: 'Collaborons',
  download: 'Télécharger',
  scroll: 'Scroll',
  menu: 'Menu',
  rights: 'Tous droits réservés',
  designedIn: 'Conçu et construit à Yaoundé · Cameroun',
  seeProject: 'Voir le projet',
  pathMeta: 'Expérience · Formation · Certifications',
  projectsCount: 'projets · CV + GitHub',
  shippedLine: 'Projets livrés, y compris en compétition.',
  shippedAccent: 'SANGO au Hackverse · SYNTRA à JUIN.',
  lifeBody: 'Le même goût du jeu : calculer, courir, poser un mot, ou rester un soir sur un écran.',
  seeWork: 'Voir',
  write: 'Écrire',
  close: 'Fermer',
  outcomes: 'Résultats',
  stack: 'Stack',
  code: 'Code',
  openProject: 'Ouvrir le projet',
};

export const levelEn: Record<string, string> = {
  Maîtrise: 'Mastery',
  Intermédiaire: 'Intermediate',
  'En apprentissage': 'Learning',
  Terminé: 'Done',
  'En cours': 'In progress',
};
