import type { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    id: 'gblrecover',
    slug: 'gblrecover',
    title: 'GBLRecover',
    subtitle: 'Revenue Assurance Platform',
    year: 2024,
    status: 'shipped',
    featured: true,
    categories: ['ai', 'software', 'data'],
    role: ['Full-Stack Developer', 'System Designer'],
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'Data Analysis'],
    problem: 'CAMTEL needed a systematic way to detect and recover revenue leakage across a large subscriber base.',
    solution: 'Built a revenue assurance platform that analyzes billing data, flags anomalies, and generates recovery workflows — turning manual audit into an automated pipeline.',
    outcome: [
      'Processed 50,606+ accounts',
      'Automated anomaly detection pipeline',
      'Reduced manual audit overhead',
    ],
    cover: 'gradient-blue',
    links: {},
  },
  {
    id: 'carburflow',
    slug: 'carburflow',
    title: 'CARBURFLOW',
    subtitle: 'Fuel Management System',
    year: 2024,
    status: 'building',
    featured: true,
    categories: ['software', 'data'],
    role: ['Product Builder', 'Mobile Developer'],
    stack: ['Flutter', 'Firebase', 'Dart'],
    problem: 'Tracking fuel consumption and distribution in real time requires a mobile-first system that works across stations and fleets.',
    solution: 'A cross-platform application for monitoring fuel flow, generating consumption reports, and flagging discrepancies — built for operators in the field.',
    cover: 'gradient-orange',
    links: {},
  },
  {
    id: 'camtel-ai',
    slug: 'camtel-ai',
    title: 'Camtel AI',
    subtitle: 'AI-Powered Telecom Solutions',
    year: 2024,
    status: 'building',
    featured: true,
    categories: ['ai', 'software'],
    role: ['AI Engineer', 'Backend Developer'],
    stack: ['Python', 'LLM', 'FastAPI', 'NLP'],
    problem: 'Telecom customer support and data processing can benefit from AI-assisted automation without replacing human operators.',
    solution: 'An AI layer that assists with customer queries, document processing, and internal data retrieval — designed to augment rather than replace human teams.',
    cover: 'gradient-mixed',
    links: {},
  },
];
